const professionals = [
  {
    id: 0,
    firstName: "David",
    lastName: "",
    type: "technician",
    skills: ["synths"],
  },
  {
    id: 1,
    firstName: "Juancar",
    lastName: "",
    type: "technician",
    skills: ["synths"],
  },
  {
    id: 2,
    firstName: "Sergio",
    lastName: "",
    type: "technician",
    skills: ["synths"],
  },
  {
    id: 3,
    firstName: "Fernando",
    lastName: "",
    type: "technician",
    skills: ["general-audio-gear"],
  },
  {
    id: 4,
    firstName: "Jorge",
    lastName: "",
    type: "technician",
    skills: ["synths", "organs", "cables-headphones-pedals"],
  },
  {
    id: 5,
    firstName: "Alejandro",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 6,
    firstName: "Bob",
    lastName: "",
    type: "technician",
    skills: ["synths"],
  },
  {
    id: 7,
    firstName: "Fernando",
    lastName: "",
    type: "technician",
    skills: ["cables-headphones-pedals"],
  },
  {
    id: 8,
    firstName: "Claudio",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 9,
    firstName: "Diego",
    lastName: "",
    type: "technician",
    skills: ["midi-controllers"],
  },
  {
    id: 10,
    firstName: "Enrique",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 11,
    firstName: "Patricio",
    lastName: "",
    type: "technician",
    skills: ["mics"],
  },
  {
    id: 12,
    firstName: "Marcelo",
    lastName: "",
    type: "technician",
    skills: ["synths"],
    location: "Zona Oeste",
  },
  {
    id: 13,
    firstName: "Augusto",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 14,
    firstName: "Andrés",
    lastName: "",
    type: "technician",
    skills: ["cables-headphones-pedals"],
  },
  {
    id: 15,
    firstName: "Nicolas",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 16,
    firstName: "Marcelo",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 17,
    firstName: "Marcelo",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 18,
    firstName: "Juan Pablo",
    lastName: "",
    type: "technician",
    skills: ["luthier"],
  },
  {
    id: 19,
    firstName: "Ramón",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 20,
    firstName: "Juan",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 21,
    firstName: "Lucas",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 22,
    firstName: "Jose",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 23,
    firstName: "Martin",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 24,
    firstName: "Sebastián",
    lastName: "",
    type: "technician",
    skills: ["general-audio-gear"],
  },
  {
    id: 25,
    firstName: "Alejandro",
    lastName: "",
    type: "technician",
    skills: ["electric-pianos", "synths", "organs"],
  },
  {
    id: 26,
    firstName: "Alejandro",
    lastName: "",
    type: "technician",
    skills: ["general-audio-gear"],
  },
  {
    id: 27,
    firstName: "Esteban",
    lastName: "",
    type: "technician",
    skills: ["general-audio-gear"],
  },
  {
    id: 28,
    firstName: "Lautaro",
    lastName: "",
    type: "technician",
    skills: ["synths"],
  },
  {
    id: 29,
    firstName: "Bruno",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 30,
    firstName: "Luis",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 31,
    firstName: "Marcelo",
    lastName: "",
    type: "technician",
    skills: ["electric-pianos"],
  },
  {
    id: 32,
    firstName: "Joaquín",
    lastName: "",
    type: "technician",
    skills: ["electric-pianos", "piano-tuner"],
  },
  {
    id: 33,
    firstName: "Marcos",
    lastName: "",
    type: "technician",
    isTecladista: true,
    skills: ["piano-tuner"],
  },
  {
    id: 34,
    firstName: "Nicolás",
    lastName: "",
    type: "technician",
    skills: ["computers"],
  },
  {
    id: 35,
    firstName: "Richard",
    type: "technician",
    skills: ["piano-mover"],
  },
  {
    id: 36,
    firstName: "Auriculares",
    lastName: "",
    type: "technician",
    skills: ["in-ears"],
  },
  {
    id: 37,
    firstName: "Blabla",
    lastName: "Audio",
    type: "technician",
    skills: ["in-ears"],
  },
  {
    id: 37,
    firstName: "Audiobla",
    type: "technician",
    skills: ["in-ears"],
  },
  {
    id: 38,
    firstName: "Auriculares",
    lastName: "",
    type: "technician",
    skills: ["in-ears"],
  },
  {
    id: 39,
    firstName: "Blabla",
    lastName: "Bags",
    type: "technician",
    skills: ["cases"],
  },
  {
    id: 40,
    firstName: "Hernán",
    lastName: "",
    type: "technician",
    skills: ["cables-headphones-pedals"],
  },
  {
    id: 41,
    firstName: "Daniel",
    lastName: "",
    type: "technician",
    skills: ["acoustic-pianos", "piano-tuner"],
  },
];

export default function (req, res) {
  res.status(200).json(professionals);
}
