const studios = [
  {
    id: 1235,
    userId: 112234,
    name: "Estudio del Sol",
    description: "Tu lugar para grabar música en Buenos Aires.",
    services: [1, 2, 3],
    status: "active",
    visibility: "open",
    pictures: ["/estudio-del-sol.jpeg"],
    location: "Palermo",
    createdAt: "2023-08-22T09:30:00.000Z",
  },
  {
    id: 1236,
    userId: 112235,
    name: "Estudio Musical Harmonía",
    description: "Excelente estudio para tus proyectos musicales.",
    services: [2, 3, 4],
    status: "active",
    visibility: "open",
    pictures: ["/estudio-harmonia.jpeg"],
    location: "Recoleta",
    createdAt: "2023-08-23T14:15:00.000Z",
  },
  {
    id: 1237,
    userId: 112236,
    name: "Estudio Rhythm Nation",
    description: "Crea música de calidad en nuestro estudio.",
    services: [1, 2, 3, 4],
    status: "active",
    visibility: "open",
    pictures: ["/estudio-rhythm-nation.jpeg"],
    location: "San Telmo",
    createdAt: "2023-08-24T11:20:00.000Z",
  },
  {
    id: 1238,
    userId: 112237,
    name: "Estudio de la Luna",
    description: "Inspiración musical bajo la luna.",
    services: [1],
    status: "active",
    visibility: "open",
    pictures: ["/estudio-luna.jpeg"],
    location: "La Boca",
    createdAt: "2023-08-25T17:40:00.000Z",
  },
  {
    id: 1239,
    userId: 112238,
    name: "Estudio de Buenos Aires",
    description: "El estudio ideal para tus proyectos musicales.",
    services: [4],
    status: "active",
    visibility: "open",
    pictures: ["/estudio-buenos-aires.jpeg"],
    location: "Belgrano",
    createdAt: "2023-08-26T10:55:00.000Z",
  },
];

export default function (req, res) {
  res.status(200).json(studios);
}
