export const products = [
  {
    _id: 1234,
    userId: 112233,
    category: "keyboard",
    brand: "Nord",
    model: "Stage 2",
    title:
      "Nord Stage 2 como nuevo dhsjah dhdsjk ajd sakjd hsjak dhsjka hdjks!!!",
    description: "",
    year: 2022,
    exchanges: true,
    status: "active",
    price: null,
    images: ["/mock-images/Nord.jpg"],
    location: "CABA",
    createdAt: "2023-08-21T13:45:00.000Z",
  },
  {
    _id: 1235,
    userId: 112234,
    condition: "used",
    category: "keyboard",
    brand: "Roland",
    model: "RD-2000",
    title: "Roland RD-2000 en excelente estado",
    description:
      "El Roland RD-2000 es un teclado de escenario líder en su clase que combina un excepcional sonido de piano acústico con una amplia variedad de sonidos de sintetizador. Perfecto para actuaciones en vivo o sesiones de estudio. Incluye todas las funciones necesarias para músicos profesionales.",
    year: 2019,
    exchanges: false,
    status: "active",
    price: null,
    visibility: "open",
    images: ["/mock-images/Roland.jpeg"],
    location: "Buenos Aires",
    createdAt: "2023-08-21T14:30:00.000Z",
  },
  {
    _id: 1236,
    userId: 112235,
    condition: "like new",
    category: "keyboard",
    brand: "Korg",
    model: "Kronos 88",
    title: "Korg Kronos 88 en perfecto estado",
    description:
      "El Korg Kronos 88 es un sintetizador y workstation líder en la industria. Con una amplia gama de sonidos y capacidades de grabación, es la elección de músicos profesionales en todo el mundo. Este teclado está en perfecto estado y listo para deslumbrar en el escenario.",
    year: 2021,
    exchanges: true,
    status: "active",
    price: 2500,
    visibility: "open",
    images: ["/mock-images/Korg.jpeg"],
    location: "Córdoba",
    createdAt: "2023-08-21T15:15:00.000Z",
  },
  {
    _id: 1237,
    userId: 112236,
    condition: "used",
    category: "keyboard",
    brand: "Yamaha",
    model: "CP88",
    title: "Yamaha CP88 en excelente estado",
    description:
      "El Yamaha CP88 es un piano de escenario profesional que ofrece un sonido de primera calidad y una experiencia de interpretación auténtica. Este teclado se encuentra en excelente estado y es ideal para músicos que buscan un rendimiento de alto nivel.",
    year: 2020,
    exchanges: false,
    status: "active",
    price: 1700,
    visibility: "open",
    images: ["/mock-images/Yamaha.jpg"],
    location: "Rosario",
    createdAt: "2023-08-21T16:00:00.000Z",
  },
  {
    _id: 1238,
    userId: 112237,
    condition: "new",
    category: "keyboard",
    brand: "Casio",
    model: "PX-560",
    title: "Casio PX-560, ¡nuevo en caja!",
    description:
      "El Casio PX-560 es un piano digital portátil que combina un sonido de alta calidad con una amplia variedad de funciones. Este teclado está nuevo en su caja original, perfecto para músicos que buscan un instrumento versátil y fácil de transportar.",
    year: 2023,
    exchanges: true,
    status: "active",
    price: 1200,
    visibility: "open",
    images: ["/mock-images/Casio.jpg"],
    location: "Mendoza",
    createdAt: "2023-08-21T17:00:00.000Z",
  },
  {
    _id: 1239,
    userId: 112238,
    condition: "used",
    category: "keyboard",
    brand: "Kawai",
    model: "MP11SE",
    title: "Kawai MP11SE en buen estado",
    description:
      "El Kawai MP11SE es un piano de escenario premium conocido por su acción de teclado auténtica y sonidos de piano realistas. Este teclado ha sido utilizado pero se encuentra en buen estado de funcionamiento. Perfecto para músicos que buscan calidad y versatilidad.",
    year: 2018,
    exchanges: false,
    status: "active",
    price: 1600,
    visibility: "open",
    images: ["/mock-images/Kawai.jpeg"],
    location: "San Juan",
    createdAt: "2023-08-21T18:00:00.000Z",
  },
  {
    _id: 1240,
    userId: 112239,
    condition: "like new",
    category: "keyboard",
    brand: "Nord",
    model: "Electro 6D 73",
    title: "Nord Electro 6D 73 en estado impecable",
    description:
      "El Nord Electro 6D 73 es un teclado que combina sonidos de órgano y piano de alta calidad con funciones versátiles de sintetizador. Este teclado está en estado impecable, ideal para músicos que buscan una amplia gama de sonidos y facilidad de uso.",
    year: 2021,
    exchanges: true,
    status: "active",
    price: 2100,
    visibility: "open",
    images: ["/mock-images/Nord-Electro.jpeg"],
    location: "La Plata",
    createdAt: "2023-08-21T19:00:00.000Z",
  },
  {
    _id: 1241,
    userId: 112240,
    condition: "used",
    category: "keyboard",
    brand: "Moog",
    model: "Subsequent 37",
    title: "Moog Subsequent 37 en excelente condición",
    description:
      "El Moog Subsequent 37 es un sintetizador analógico legendario conocido por su sonido cálido y potente. Este teclado ha sido usado pero se encuentra en excelente condición de funcionamiento. Perfecto para músicos que buscan sonidos de sintetizador únicos.",
    year: 2017,
    exchanges: false,
    status: "active",
    price: 1900,
    visibility: "open",
    images: ["/mock-images/Moog.jpg"],
    location: "Bahía Blanca",
    createdAt: "2023-08-21T20:00:00.000Z",
  },
  {
    _id: 1242,
    userId: 112241,
    condition: "like new",
    category: "keyboard",
    brand: "Korg",
    model: "SV-2",
    title: "Korg SV-2, casi nuevo",
    description:
      "El Korg SV-2 es un piano de escenario que rinde homenaje a los legendarios teclados electro-mecánicos. Este teclado está en condición casi nueva y ofrece una amplia variedad de sonidos vintage. Perfecto para músicos que buscan ese toque retro.",
    year: 2022,
    exchanges: true,
    status: "active",
    price: 1400,
    visibility: "open",
    images: ["/mock-images/Korg-SV2.jpeg"],
    location: "Tucumán",
    createdAt: "2023-08-21T21:00:00.000Z",
  },
  {
    _id: 1243,
    userId: 112242,
    condition: "used",
    category: "keyboard",
    brand: "Nord",
    model: "Lead A1",
    title: "Nord Lead A1 en buen estado",
    description:
      "El Nord Lead A1 es un sintetizador virtual analógico conocido por su sonido fresco y versátil. Este teclado ha sido usado pero se encuentra en buen estado y ofrece un mundo de posibilidades sonoras. Ideal para músicos creativos.",
    year: 2016,
    exchanges: false,
    status: "active",
    price: 1300,
    visibility: "open",
    images: ["/mock-images/NordLeadA1.jpg"],
    location: "Neuquén",
    createdAt: "2023-08-21T22:00:00.000Z",
  },
  {
    _id: 1244,
    userId: 112243,
    condition: "new",
    category: "keyboard",
    brand: "Arturia",
    model: "KeyLab Essential 61",
    title: "Arturia KeyLab Essential 61, ¡nuevo en caja!",
    description:
      "El Arturia KeyLab Essential 61 es un controlador MIDI versátil que brinda una experiencia de producción musical completa. Este teclado está nuevo en su caja original y es perfecto para músicos que buscan control y creatividad en sus proyectos.",
    year: 2023,
    exchanges: true,
    status: "active",
    price: 600,
    visibility: "open",
    images: ["/mock-images/keylab-essential-61-image.png"],
    location: "Salta",
    createdAt: "2023-08-21T23:00:00.000Z",
  },
];

export default function (req, res) {
  res.status(200).json(products);
}
